export const ShopRoute = '/shop'
export const HomeRoute = '/'
export const RegisterRoute='/registration'
export const AuthRoute='/authentication'
export const NewsRoute = '/news'
export const LOCAL_API_URL = 'http://porsche-server-production.up.railway.app'